---
- name: Manage ECS Fargate services via AWS CLI
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cluster_name: diet-app-cluster
    frontend_service: frontend-service
    backend_service: backend-service
    region: ap-south-1

  tasks:
    - name: Ensure frontend ECS service desired count = 1
      ansible.builtin.command: >
        aws ecs update-service
        --cluster {{ cluster_name }}
        --service {{ frontend_service }}
        --desired-count 1
        --region {{ region }}
      register: frontend_update
      changed_when: "'service' in frontend_update.stdout"

    - name: Ensure backend ECS service desired count = 1
      ansible.builtin.command: >
        aws ecs update-service
        --cluster {{ cluster_name }}
        --service {{ backend_service }}
        --desired-count 1
        --region {{ region }}
      register: backend_update
      changed_when: "'service' in backend_update.stdout"

    - name: List running tasks for frontend
      ansible.builtin.command: >
        aws ecs list-tasks
        --cluster {{ cluster_name }}
        --service-name {{ frontend_service }}
        --region {{ region }}
      register: frontend_tasks

    - name: List running tasks for backend
      ansible.builtin.command: >
        aws ecs list-tasks
        --cluster {{ cluster_name }}
        --service-name {{ backend_service }}
        --region {{ region }}
      register: backend_tasks

    - name: Display frontend task ARNs
      debug:
        var: frontend_tasks.stdout_lines

    - name: Display backend task ARNs
      debug:
        var: backend_tasks.stdout_lines
