---
- name: Manage ECS Fargate services
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cluster_name: diet-app-cluster
    frontend_service: frontend-service
    backend_service: backend-service
    region: ap-south-1

  tasks:
    - name: Ensure frontend ECS service is running desired count
      amazon.aws.ecs_service:
        cluster: "{{ cluster_name }}"
        service: "{{ frontend_service }}"
        desired_count: 1
        state: present
        region: "{{ region }}"

    - name: Ensure backend ECS service is running desired count
      amazon.aws.ecs_service:
        cluster: "{{ cluster_name }}"
        service: "{{ backend_service }}"
        desired_count: 1
        state: present
        region: "{{ region }}"

    - name: List running tasks for frontend
      amazon.aws.ecs_task_info:
        cluster: "{{ cluster_name }}"
        service_name: "{{ frontend_service }}"
        region: "{{ region }}"
      register: frontend_tasks

    - name: List running tasks for backend
      amazon.aws.ecs_task_info:
        cluster: "{{ cluster_name }}"
        service_name: "{{ backend_service }}"
        region: "{{ region }}"
      register: backend_tasks

    - name: Display frontend task ARNs
      debug:
        var: frontend_tasks.tasks

    - name: Display backend task ARNs
      debug:
        var: backend_tasks.tasks
