# prometheus.yml - Prometheus Configuration for Diet Plan API

global:
  scrape_interval: 15s       # How often to scrape targets
  evaluation_interval: 15s   # How often to evaluate rules
  scrape_timeout: 10s        # Timeout for scraping
  
  external_labels:
    monitor: 'diet-api-monitor'
    environment: 'production'

# Scrape configurations
scrape_configs:
  # Diet Plan API
  - job_name: 'diet-plan-api'
    
    metrics_path: '/metrics'
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    
    static_configs:
      - targets: 
          # Mac/Windows Docker Desktop: use host.docker.internal
          - 'host.docker.internal:6060'
          # Linux: replace with your machine's IP address
          # - '192.168.1.100:6060'
        
        labels:
          service: 'diet-plan-api'
          application: 'flask-backend'
          environment: 'production'
          team: 'backend'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          environment: 'monitoring'
